application/models/db_models.py
from __future__ import annotations

from application import db


class Users(db.Model):
    __tablename__ = 'users'
    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)


class Customers(db.Model):
    __tablename__ = 'customers'

    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000), nullable=False)
    email = db.Column(db.String(100), unique=True)
    address = db.Column(db.String(100), nullable=False)
    phone_number = db.Column(db.String(100), nullable=False)


class Products(db.Model):
    __tablename__ = 'products'
    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    price = db.Column(db.Float(100), nullable=False)


class Invoice(db.Model):
    __tablename__ = 'invoices'
    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    customer_id = db.Column(
        db.Integer, db.ForeignKey(
            'customers.id',
        ), nullable=False,
    )


class InvoiceMaps(db.Model):
    __tablename__ = 'invoicemaps'
    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(
        db.Integer, db.ForeignKey(
            'customers.id',
        ), nullable=False,
    )
    product_id = db.Column(
        db.Integer, db.ForeignKey(
            'products.id',
        ), nullable=False,
    )

application/__init__.py
from __future__ import annotations

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.DevelopmentConfig')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    login_manager.init_app(app)
    return app

application/routes.py
from __future__ import annotations

import datetime
from os import path

from application import db
from application import login_manager
from application.models.db_models import Customers
from application.models.db_models import Products
from application.models.db_models import Users
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import send_from_directory
from flask import url_for
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user


invoice = Blueprint('invoice', __name__)


@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))


@invoice.route('/')
@login_required
def index():
    return redirect(url_for('.generate_invoice'))


@invoice.route('/favicon.ico')
def favicon():
    return send_from_directory(
        path.join(
            invoice.root_path,
            'static',
        ),
        'images/apl.png',
        mimetype='image/x-icon',
    )


@invoice.route('/login', methods=['GET', 'POST'])
def login():
    email = request.form.get('username')
    password = request.form.get('password')
    print(password)
    user = Users.query.filter_by(email=email).first()
    if request.method == 'POST':
        if user:
            flash(f'Welcome {email}', 'success')
            login_user(user)
            return redirect(url_for('.index'))
        else:
            flash('Invalid username or password', 'danger')
    return render_template('login.html')


@invoice.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('.login'))


@invoice.route('/generate_invoice')
@login_required
def generate_invoice():
    customers = Customers.query.all()
    products = Products.query.all()
    date_time = datetime.datetime.today().strftime('%d-%m-%Y')
    return render_template(
        'invoice_generator.html',
        customers=customers,
        products=products,
        date_time=date_time,
    )


@invoice.route('/manage_customers', methods=['GET'])
@login_required
def manage_customers():
    customers = Customers.query.all()
    return render_template('customers.html', customers=customers)


@invoice.route('/add_customer', methods=['POST'])
@login_required
def add_customer():
    name = request.form.get('customer-name')
    address = request.form.get('customer-address')
    email = request.form.get('customer-email')
    phone_number = request.form.get('customer-phone')
    new_customer = Customers(
        name=name, address=address,
        email=email, phone_number=phone_number,
    )
    try:
        db.session.add(new_customer)
        db.session.commit()
        flash('New customer successfully added', 'success')
    except Exception as e:
        print(e)
        db.session.rollback()
        db.session.flush()
        flash('Some customer details entered are not proper', 'danger')
    return redirect(url_for('manage_customers'))


@invoice.route('/manage_invoice_items', methods=['GET'])
@login_required
def manage_invoice_items():
    products = Products.query.all()
    return render_template('add_products_for_invoice.html', products=products)


@invoice.route('/add_product', methods=['POST'])
@login_required
def add_product():
    name = request.form.get('item-name')
    price = request.form.get('item-price')
    new_product = Products(name=name, price=price)
    try:
        db.session.add(new_product)
        db.session.commit()
        flash('New item successfully added', 'success')
    except Exception as e:
        print(e)
        db.session.rollback()
        db.session.flush()
        flash('Item could not be added', 'danger')
    return redirect(url_for('manage_invoice_items'))


@invoice.route('/get_customer_details', methods=['GET'])
@login_required
def get_customer_details():
    customer_id = request.args.get('customer_id')
    customer = Customers.query.filter_by(id=int(customer_id)).first()
    if not customer:
        return {'ERROR': 'FAILED'}

    return {
        'name': customer.name,
        'email': customer.email,
        'address': customer.address,
        'phone_number': customer.phone_number,
    }


@invoice.route('/edit_customer', methods=['GET', 'POST'])
@login_required
def edit_customer():
    try:
        customer_id = request.form.get('edited_customer_id')
        name = request.form.get('edited_customer_name')
        address = request.form.get('edited_customer_address')
        email = request.form.get('edited_customer_email')
        phone_number = request.form.get('edited_customer_phone')

        valid_customer = Customers.query.filter_by(id=int(customer_id)).first()
        if valid_customer:
            if valid_customer.name != name:
                valid_customer.name = name

            if valid_customer.address != address:
                valid_customer.address = address

            if valid_customer.email != email:
                valid_customer.email = email

            if valid_customer.phone_number != phone_number:
                valid_customer.phone_number = phone_number

            db.session.commit()
            flash('Successfully updated the customer details', 'success')
            return redirect(url_for('.manage_customers'))
        else:
            raise Exception('Invalid customer details')
    except Exception as e:
        print(e)
        db.session.rollback()
        db.session.flush()
        flash('Customer could not be updated, please check the form', 'danger')
        return redirect(url_for('.manage_customers'))


@invoice.route('/login_2', methods=['GET'])
@login_required
def login_2():
    return render_template('login_2.html')


@invoice.route('/get_product_details', methods=['GET'])
@login_required
def get_product_details():
    """ Get all product details using product ID"""

    product_id = request.args.get('product_id')
    product = Products.query.filter_by(id=int(product_id)).first()
    if not product:
        return {'ERROR': 'FAILED'}

    return {
        'name': product.name,
        'price': product.price,
    }


@invoice.route('/edit_product', methods=['POST'])
@login_required
def edit_product():
    try:
        product_id = request.form.get('update_product_id')
        name = request.form.get('update_item_name')
        price = request.form.get('update_item_price')

        valid_product = Products.query.filter_by(id=int(product_id)).first()
        if valid_product:
            if valid_product.name != name:
                valid_product.name = name

            if valid_product.price != price:
                valid_product.price = price

            db.session.commit()
            flash('Successfully updated the product', 'success')
            return redirect(url_for('.manage_invoice_items'))

        else:
            raise Exception('Invalid product')

    except Exception as e:
        print(e)
        db.session.rollback()
        db.session.flush()
        flash('Product could not be updated, please check the form', 'danger')
        return redirect(url_for('.manage_invoice_items'))


@invoice.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    return render_template('dashboard.html')


@invoice.route('/dummy_data', methods=['GET', 'POST'])
@login_required
def dummy_data():
    if request.method == 'POST':
        if 'delete_all' in request.form:
            delete_all = request.form['delete_all']
        else:
            delete_all = None

        if delete_all:
            try:
                Customers.query.delete()
                Products.query.delete()
                db.session.commit()
                flash('Deleted all data of customers and products!', 'success')
            except Exception:
                db.session.rollback()
                db.session.flush()
                flash(
                    'Could not delete data of customers and products!',
                    'danger',
                )
            return render_template('dummy_data.html')

        customer_count = int(request.form['customer_count'])
        product_count = int(request.form['product_count'])
        try:
            if customer_count:
                for count in range(0, customer_count):
                    new_customer = Customers(
                        name=f'customer_{count}',
                        email=f'customer_{count}@gmail.com',
                        address='76890,KA Germany',
                        phone_number='908728738767',
                    )
                    db.session.add(new_customer)
                db.session.commit()

            if product_count:
                for count in range(0, product_count):
                    new_products = Products(
                        name=f'product_{count}', price=count+180,
                    )
                    db.session.add(new_products)
                db.session.commit()

        except Exception as e:
            print(e)
            db.session.rollback()
            db.session.flush()

    return render_template('dummy_data.html')

# @invoice.route('/generate_customer_invoice', methods=['GET','POST'])
# @login_required
# def generate_customer_invoice():
#     today = datetime.today().strftime("%d/%m/%Y")
#     invoice_number = 123
#     from_addr = {
#         'company_name': 'Python Tip',
#         'addr1': '12345 Sunny Road',
#         'addr2': 'Sunnyville, CA 12345'
#     }
#     to_addr = {
#         'company_name': 'Acme Corp',
#         'person_name': 'John Dilly',
#         'person_email': 'john@example.com'
#     }
#     items = [
#         {
#             'title': 'website design',
#             'charge': 300.00
#         },{
#             'title': 'Hosting (3 months)',
#             'charge': 75.00
#         },{
#             'title': 'Domain name (1 year)',
#             'charge': 10.00
#         }
#     ]
#     duedate = "August 1, 2018"

application/templates/add_products_for_invoice.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">{% block title %}Create New Item{% endblock %}</li>
{% endblock %}

{% block content %}
  <h1>Manage Invoice Items</h1>
  <hr/>

  <button class="btn btn-sm" style="border: 1px solid hsl(198, 83%, 24%); font-size:15px;color:hsl(198, 83%, 24%);"data-toggle="modal" data-title="Add" data-target="#add-item" type="button">
    <i class="fa-solid fa-cart-plus"></i> Products
  </button>

  <div class="table-responsive mt-2">
    <table class="table table-striped table-responsive">
      <thead style="background-color:hsl(198, 83%, 24%);" class="text-white">
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody id="vacation-table-body">
      {% for product in products %}
        <tr>
          <td>{{ product.name }}</td>
          <td>{{ product.price }}</td>
          <td>{{ product.name }}</td>
          <td>
            <i class="fa-solid fa-pen-to-square me-3 open_edit_product_dialog"
                id="edit_{{product.name}}"
                data-toggle="modal"
                data-title="Update"
                data-id="{{product.id}}"
                data-target="#edit_{{product.name}}"
                style="color:green;"></i>
            <i class="fa-solid fa-trash" id="delete_{{product.name}}" style="color:red;"></i>
          </td>
        </tr>

        <div class="modal fade " id="edit_{{product.name}}" tabindex="-1">
          <div class="modal-dialog">
            <form id="edit-product-form" action="{{url_for('invoice.edit_product')}}" method="POST">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="Heading">Edit Invoice Item</h4>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <span>×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <input type="hidden" id="update_product_id" name="update_product_id" >
                  <div class="form-group">
                    <label for="update_item_name"><b>Product Name</b></label>
                    <input type="text" class="form-control" id="update_item_name" name="update_item_name" value="" required></input>
                    <small id="emailHelp" class="form-text text-muted">Example: Screwdriver </small>
                  </div>

                  <div class="form-group">
                      <label for="">Currency</label>
                      <select class="form-control" name="currency" id="currency">
                          <option value="1">$</option>
                          <option value="2">€</option>
                      </select>
                  </div>

                  <div class="form-group">
                    <label for="item-price"><b>Price</b></label>
                    <input type="text"
                      class="form-control" id="update_item_price" name="update_item_price" value="" required></input>
                    <small id="emailHelp" class="form-text text-muted">Example: 49.99$ </small>
                  </div>



                </div>
                <div class="modal-footer ">
                  <button class="btn btn-success btn-lg" style="width: 100%;">
                    <i class="fa fa-save"></i> Update
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      {% endfor %}
      </tbody>
    </table>
  </div>


  <div class="modal fade" id="add-item" tabindex="-1">
    <div class="modal-dialog">
      <form id="edit-vacation-form" action="{{url_for('invoice.add_product')}}" method="POST">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="Heading">Add Invoice Item</h4>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              <span>×</span>
            </button>
          </div>
          <div class="modal-body">

            <div class="form-group">
              <label for="item-name"><b>Product Name</b></label>
              <input type="text" class="form-control" id="item-name" name="item-name" value="" required></input>
              <small id="emailHelp" class="form-text text-muted">Example: Screwdriver </small>
            </div>

            <div class="form-group">
                <label for="">Currency</label>
                <select class="form-control" name="currency" id="currency">
                    <option value="1">$</option>
                    <option value="2">€</option>
                </select>
            </div>

            <div class="form-group">
              <label for="item-price"><b>Price</b></label>
              <input type="text" class="form-control" id="item-price" name="item-price" value="" required></input>
              <small id="emailHelp" class="form-text text-muted">Example: 49.99$ </small>
            </div>



          </div>
          <div class="modal-footer ">
            <button class="btn btn-success btn-lg" style="width: 100%;">
              <i class="fa fa-save"></i> Add
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>


{% endblock %}

{% block scripts %}
  <script>
    $(document).on("click", ".open_edit_product_dialog", function() {
      var product_id = $(this).data('id')
      $.ajax({
            type: "GET",
            url: "{{url_for('invoice.get_product_details')}}",
            data: {"product_id":   product_id },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function(result){
                if (!result["ERROR"]){
                  $(".modal-body #update_item_name").val(result["name"]);
                  $(".modal-body #update_item_price").val(result["price"]);
                  $(".modal-body #update_product_id").val(product_id);
                } else{
                    console.log("wasuhjkashd");
                }
            }
        });
    });
  </script>
{% endblock %}

application/templates/customers.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">{% block title %}Create New Customer{% endblock %}</li>
{% endblock %}

{% block content %}
  <h1>Manage Customers</h1>
  <hr/>

  <button class="btn btn-sm" style="border: 1px solid #373756; font-size:15px;color:#373756;" data-toggle="modal" data-title="Add" data-target="#add-customer" type="button">
    <i class="fa-solid fa-user-plus"></i> Customer
  </button>

  <div class="table-responsive mt-2">
    <table class="table table-striped table-responsive">
      <thead style="background-color:#373756;" class="text-white">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody id="vacation-table-body">
      {% for customer in customers %}
        <tr>
          <td>{{ customer.name }}</td>
          <td>{{ customer.email }}</td>
          <td>{{ customer.address }}</td>
          <td>{{customer.phone_number}} </td>
          <td>
            <i class="open_edit_customer_dialog fa-solid fa-pen-to-square me-3" data-toggle="modal" data-title="Add"
                id="edit_{{customer.name}}" style="color:green;" data-id="{{customer.id}}" data-target="#edit_{{customer.name}}" type="button"></i>
            <i class="fa-solid fa-trash" id="delete_{{customer.name}}" style="color:red;"></i>
          </td>
        </tr>

        <div class="modal fade" id="edit_{{customer.name}}" tabindex="-1">
          <div class="modal-dialog">
            <form id="edit-vacation-form" action="{{url_for('invoice.edit_customer')}}" method="POST">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="Heading">Edit customer</h4>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <span>×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <input type="hidden" id="edited_customer_id" name="edited_customer_id">
                  <div class="form-group">
                    <label for="customer-name"><b>Name</b></label>
                    <input type="text" class="form-control" id="edited_customer_name" name="edited_customer_name" value="" required></input>
                    <small id="emailHelp" class="form-text text-muted">Example: Aleem Khan</small>
                  </div>

                  <div class="form-group">
                    <label for="customer-email"><b>Email</b></label>
                    <input class="form-control" id="edited_customer_email" name="edited_customer_email" value="" required></input>
                    <small id="emailHelp" class="form-text text-muted">Example: aleemkhan@gmail.com</small>
                  </div>

                  <div class="form-group">
                    <label for="customer-address"><b>Address</b></label>
                    <textarea class="form-control" id="edited_customer_address" name="edited_customer_address" value="" required></textarea>
                    <small id="emailHelp" class="form-text text-muted">Example: 76185,KA Germany </small>
                  </div>

                  <div class="form-group">
                    <label for="customer-phone"><b>Phone Number</b></label>
                    <input class="form-control" id="edited_customer_phone" name="edited_customer_phone" value="" required></input>
                    <small id="emailHelp" class="form-text text-muted">Example: +49-17656525546</small>
                  </div>

                </div>

                <div class="modal-footer ">
                  <button class="btn btn-success btn-lg" style="width: 100%;">
                    Update
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      {% endfor %}
      </tbody>
    </table>
  </div>


  <div class="modal fade" id="add-customer" tabindex="-1">
    <div class="modal-dialog">
      <form id="edit-vacation-form" action="{{url_for('invoice.add_customer')}}" method="POST">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="Heading">Add customer</h4>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              <span>×</span>
            </button>
          </div>
          <div class="modal-body">

            <div class="form-group">
              <label for="customer-name"><b>Name</b></label>
              <input type="text" class="form-control" id="customer-name" name="customer-name" value="" required></input>
              <small id="emailHelp" class="form-text text-muted">Example: Aleem Khan</small>
            </div>

            <div class="form-group">
              <label for="customer-email"><b>Email</b></label>
              <input class="form-control" id="customer-email" name="customer-email" value="" required></input>
              <small id="emailHelp" class="form-text text-muted">Example: aleemkhan@gmail.com</small>
            </div>

            <div class="form-group">
              <label for="customer-address"><b>Address</b></label>
              <textarea class="form-control" id="customer-address" name="customer-address" value="" required></textarea>
              <small id="emailHelp" class="form-text text-muted">Example: 76185,KA Germany </small>
            </div>

            <div class="form-group">
              <label for="customer-phone"><b>Phone Number</b></label>
              <input class="form-control" id="customer-phone" name="customer-phone" value="" required></input>
              <small id="emailHelp" class="form-text text-muted">Example: +49-17656525546</small>
            </div>

          </div>

          <div class="modal-footer ">
            <button class="btn btn-success btn-lg" style="width: 100%;">
              <i class="fa fa-add"></i> Add
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>




{% endblock %}

{% block scripts %}
  <script>
    $(document).on("click", ".open_edit_customer_dialog", function() {
      var customer_id = $(this).data('id')
      $.ajax({
            type: "GET",
            url: "{{url_for('invoice.get_customer_details')}}",
            data: {"customer_id":   customer_id },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function(result){
                if (!result["ERROR"]){
                  $(".modal-body #edited_customer_name").val(result["name"]);
                  $(".modal-body #edited_customer_email").val(result["email"]);
                  $(".modal-body #edited_customer_address").val(result["address"]);
                  $(".modal-body #edited_customer_phone").val(result["phone_number"]);
                  $(".modal-body #edited_customer_id").val(customer_id);
                } else{
                    console.log("wasuhjkashd");
                }
            }
        });
    });

  </script>
{% endblock %}

application/templates/dummy_data.html
{% extends 'base.html' %}
{% block breadcrumb %}
  <li class="breadcrumb-item">{% block title %}{% endblock %}</li>
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <form action="{{url_for('invoice.dummy_data')}}" method="post">
                        <div class="col-md-6">
                                <div class="col-md-3">
                                    <label for="customers">Customers</label>
                                    <input type="number" id="customer_count" name="customer_count" class="form-control">
                                </div>

                                <div class="col-md-3">
                                    <label for="products">Products</label>
                                    <input type="number" id="product_count" name="product_count" class="form-control">
                                </div>

                                <div class="col-md-3 mt-3">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                        </div>

                        <div class="col-md-6">
                            <div class="col-md-3 mt-4">
                                <button class="btn btn-danger" type="submit" name="delete_all" value="True">Delete All</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

application/templates/navigation.html
<nav
  class="navbar navbar-dark static-top border border-bottom-4 rounded-3"
  style="height: 60px; background-color: hsl(0, 0%, 100%)"
>
  <div class="container-fluid rounded-2">
    <a class="navbar-brand text-dark" href="/">
      <img
        src="{{ url_for('static',filename='images/apl.png') }}"
        style="height: 30px; color: rgb(168, 28, 28)"
        alt="e-invoice"
      />
      InGen
      <button class="btn btn-link btn-sm" id="" href="#">
        <i class="fas fa-bars"></i>
      </button>
    </a>

    <ul class="navbar-brand ml-md-2" style="list-style: none">
      <li class="dropdown no-arrow text-dark">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="userDropdown"
          data-toggle="dropdown"
        >
          <i class="fas fa-user-circle fa-fw"></i>
          <span class="hidden-xs">{{ current_user.name }}</span>
        </a>
        <div class="dropdown-menu dropdown-menu-left no-arrow">
          <a
            class="dropdown-item text-dark"
            href="#"
            data-toggle="modal"
            data-target="#logoutModal"
          >
            <i class="fa fa-sign-out-alt"></i> Logout
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

application/templates/sidebar.html
<ul class="sidebar navbar-nav rounded-1">
  <li class="nav-item  {% if 'dashboard' in request.url %} border-5 rounded-4 active {% endif %}"
  {% if 'dashboard' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="{{ url_for('invoice.dashboard') }}">
        <i class="fa-solid fa-house"></i>
        <span>Dashboard</span>
      </a>


    </li>
    <!-- <li class="nav-item">
      <a class="nav-link" href="{{ url_for('invoice.generate_invoice') }}">
        <i class="fas fa-file-invoice"></i>
        <span>Generate E-Invoice</span>
      </a>
    </li> -->
    <li class="nav-item  {% if 'generate_invoice' in request.url %} border-5 rounded-4 active {% endif %}"
        {% if 'generate_invoice' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="{{ url_for('invoice.generate_invoice') }}">
        <i class="fas fa-file-invoice"></i>
        <span>Generate E-Invoice</span>
      </a>
    </li>


    <li class="nav-item {% if 'manage_customers' in request.url %} border-5 rounded-4 active {% endif %}"
        {% if 'manage_customers' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="{{ url_for('invoice.manage_customers') }}">
        <i class="fa-solid fa-users"></i>
        <span>Customers</span>
      </a>
    </li>

    <li class="nav-item {% if 'manage_invoice_items' in request.url %} border-5 rounded-4  active {% endif %}"
    {% if 'manage_invoice_items' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}
    >
      <a class="nav-link" href="{{ url_for('invoice.manage_invoice_items') }}">
        <i class="fa-solid fa-hand-holding-dollar"></i>
        <span>Products</span>
      </a>
    </li>
    <li class="nav-item {% if 'settings' in request.url %} border-5 rounded-4 active {% endif %}"
    {% if 'product_groups' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="#">
        <i class="fa-solid fa-sitemap"></i>
        <span>Groups</span>
      </a>
    </li>
    <li class="nav-item {% if 'settings' in request.url %} border-5 rounded-4 active {% endif %}"
    {% if 'settings' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="#">
        <i class="fa-solid fa-sliders"></i>
        <span>Settings</span>
      </a>
    </li>

    <li class="nav-item {% if 'dummy_data' in request.url %} border-5 rounded-4 active {% endif %}"
    {% if 'dummy_data' in request.url %} style="background-color:rgb(241, 241, 241);width: 100%;" {% endif %}>
      <a class="nav-link" href="{{ url_for('invoice.dummy_data') }}">
        <i class="fa-solid fa-sliders"></i>
        <span>dummy_data</span>
      </a>
    </li>

  </ul>